version: "3.7"
services:
  frontend:
    build: ./frontend
    image: horners/frontend:latest
    container_name: frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

  backend:
    build: ./backend
    image: horners/backend:latest
    container_name: backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
      DATABASE_URI: 'mysql+pymysql://root:password@terraform-20201121123706355700000003.cml50gxwj1hn.eu-west-1.rds.amazonaws.com:3306/users'
      TEST_DATABASE_URI: 'mysql+pymysql://root:password@terraform-20201121123706355700000003.cml50gxwj1hn.eu-west-1.rds.amazonaws.com:3306/testdb'