- hosts: 34.251.103.213
  become: true
  tasks:
  - name: Copy pytest-install.sh
    copy:
      src: pytest-install.sh
      dest: /root
      owner: root
  - name: Run pytest-install.sh
    command: sh /root/pytest-install.sh

  - name: Copy jenkins-install.sh
    copy:
      src: jenkins-install.sh
      dest: /root
      owner: root
  - name: Copy docker-install.sh
    copy:
      src: docker-install.sh
      dest: /root
      owner: root
  - name: Run docker-install.sh
    command: sh /root/docker-install.sh

  - name: Copy jenkins-install.sh
    copy:
      src: jenkins-install.sh
      dest: /root
      owner: root

  - name: Run jenkins-install.sh
    command: sh /root/jenkins-install.sh

  - name: Fetch initial jenkins password
    fetch:
      src: /root/jenkinsPass
      dest: /home/ubuntu/terra1/ansible/returns/VM-IP