- hosts: 34.243.200.215
  become: true
  tasks:
  - name: Copy docker-install.sh
    copy:
      src: docker-install.sh
      dest: /home/ubuntu
      owner: ubuntu
  - name: Run docker-install.sh
    command: sh /home/ubuntu/docker-install.sh